SELECT 
    A.ID, 
    CASE
        WHEN (A.TITLE = 1) THEN 'CRITICAL'
        WHEN (A.TITLE = 2) THEN 'HIGH'
        WHEN (A.TITLE = 3) THEN 'MEDIUM'
        ELSE 'LOW'
        END AS COLONY_NAME
FROM (SELECT
        ID,
        SIZE_OF_COLONY,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS TITLE 
    FROM ECOLI_DATA) AS A
ORDER BY A.ID ASC;